services:
  - type: web
    name: novate-api
    runtime: docker
    plan: starter
    envVars:
      - key: APP_NAME
        value: "Novate Platform"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://novacollect.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d8065567r5hc73bbm9l0-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: novate
      - key: DB_USERNAME
        value: novate_user
      - key: DB_PASSWORD
        value: 5pkXouBIOLv4hCQxk7lrjWRydz395Lop
      - key: DB_SSLMODE
        value: require
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: FRONTEND_URL
        value: https://novacollect-frontend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:3000,http://localhost:5173,http://localhost:8000,https://novacollect.onrender.com,https://novacollect-frontend.onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: localhost:3000,localhost:5173,localhost:8000,novacollect.onrender.com,novacollect-frontend.onrender.com
      - key: L5_SWAGGER_CONST_HOST
        value: https://novacollect.onrender.com/api/v1
